# Generated by Django 4.0.5 on 2022-07-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_order_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('paymentstatus', models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], max_length=100)),
                ('orderstatus', models.CharField(choices=[('panding', 'panding'), ('accepted', 'accepted'), ('on the way', 'on the way'), ('delivery', 'delivery')], default='panding', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=200, upload_to='')),
                ('price', models.IntegerField()),
                ('descriptions', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('darjan', 'Darjan')], default='Kg', max_length=100)),
                ('totalquantites', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.product')),
            ],
        ),
    ]
