# Generated by Django 4.0.5 on 2022-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='orderstatus',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('on the way', 'on the way'), ('delivery', 'delivery')], default='pending', max_length=100),
        ),
    ]
