# Generated by Django 4.0.6 on 2022-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
